# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1goO8OSskrbfWdNOJ0gT8wLy1yqdvauVx

##MUSTARD dataset
"""

from google.colab import files

# Upload dataset from local setup
uploaded = files.upload()

print("✓ File uploaded successfully!")

import json

# JSON file
with open('sarcasm_data.json', 'r') as f:
    mustard_data = json.load(f)

print(f"✓ Loaded {len(mustard_data)} samples")
print(f"✓ First few keys: {list(mustard_data.keys())[:5]}")

# Load One sample
first_key = list(mustard_data.keys())[0]
print(f"\n✓ Sample data:")
print(f"  Utterance: {mustard_data[first_key]['utterance']}")
print(f"  Speaker: {mustard_data[first_key]['speaker']}")
print(f"  Sarcasm: {mustard_data[first_key]['sarcasm']}")

# Required packages
!pip install sentence-transformers scikit-learn torch -q

print("✓ Installation complete!")

import json
import numpy as np
from sklearn.model_selection import train_test_split
from sentence_transformers import SentenceTransformer

print("Step 1: Loading data")
# Data loading
with open('sarcasm_data.json', 'r') as f:
    mustard_data = json.load(f)

print(f"✓ Loaded {len(mustard_data)} samples")

print("\nStep 2: Loading sentence encoder...")
# Sentence encoder loading
encoder = SentenceTransformer('all-MiniLM-L6-v2')
print("✓ Encoder loaded!")

print("\nStep 3: Processing features for 3 clients...")

# Storage
utterance_features = []
context_features = []
speaker_features = []
labels = []

# All unique speakers
speakers = set()
for key, item in mustard_data.items():
    speakers.add(item['speaker'])
    for sp in item['context_speakers']:
        speakers.add(sp)

speaker_to_idx = {sp: idx for idx, sp in enumerate(sorted(speakers))}
print(f"✓ Found {len(speakers)} unique speakers")

# Processing each sample
print("✓ Encoding utterances and contexts (this may take 2-3 minutes)...")

for i, (key, item) in enumerate(mustard_data.items()):
    # Progress every 100 samples
    if (i + 1) % 100 == 0:
        print(f"  Processed {i+1}/{len(mustard_data)} samples...")

    # Client 1: Utterance features (384-dim)
    utt_feat = encoder.encode(item['utterance'])
    utterance_features.append(utt_feat)

    # Client 2: Context features (average of context)
    if item['context']:
        ctx_encodings = encoder.encode(item['context'])
        ctx_feat = ctx_encodings.mean(axis=0)
    else:
        ctx_feat = np.zeros(384)
    context_features.append(ctx_feat)

    # Client 3: Speaker features (one-hot encoding)
    speaker_feat = np.zeros(len(speaker_to_idx))
    speaker_feat[speaker_to_idx[item['speaker']]] = 1
    speaker_features.append(speaker_feat)

    # Label (we convert True/False to 1/0)
    labels.append(1 if item['sarcasm'] else 0)

# Numpy arrays
utterance_features = np.array(utterance_features)
context_features = np.array(context_features)
speaker_features = np.array(speaker_features)
labels = np.array(labels)

print("\n✓ Feature extraction complete!")
print(f"  Utterance features: {utterance_features.shape}")
print(f"  Context features: {context_features.shape}")
print(f"  Speaker features: {speaker_features.shape}")
print(f"  Labels: {labels.shape}")
print(f"  Sarcasm rate: {labels.mean():.1%}")

print("\nStep 4: Splitting data (70% train, 15% val, 15% test)...")

# Train/val/test split
train_idx, temp_idx = train_test_split(
    np.arange(len(labels)),
    test_size=0.3,
    random_state=42,
    stratify=labels
)
val_idx, test_idx = train_test_split(
    temp_idx,
    test_size=0.5,
    random_state=42,
    stratify=labels[temp_idx]
)

print(f"✓ Train: {len(train_idx)} samples ({len(train_idx)/len(labels):.1%})")
print(f"✓ Val: {len(val_idx)} samples ({len(val_idx)/len(labels):.1%})")
print(f"✓ Test: {len(test_idx)} samples ({len(test_idx)/len(labels):.1%})")

print("\nStep 5: Saving preprocessed data...")

# Save all files
np.save('mustard_utterance_features.npy', utterance_features)
np.save('mustard_context_features.npy', context_features)
np.save('mustard_speaker_features.npy', speaker_features)
np.save('mustard_labels.npy', labels)
np.save('mustard_train_idx.npy', train_idx)
np.save('mustard_val_idx.npy', val_idx)
np.save('mustard_test_idx.npy', test_idx)

print("✓ Saved 7 .npy files!")
print("\n" + "="*50)
print("✓✓✓ PREPROCESSING COMPLETE! ✓✓✓")
print("="*50)

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import numpy as np
import random
import math
import pandas as pd
from sklearn.metrics import f1_score, precision_score, recall_score, confusion_matrix
import time


def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(42)

# IMPROVED CONFIG
T = 80  # Training rounds (fewer needed for this comparatively smaller dataset)
η_initial = 0.005  # Lower learning rate for multimodal data
η_min = 0.0005
α = 0.5  # Consensus rate
batch_size = 32  # Smaller batch for 690 samples
device = 'cuda' if torch.cuda.is_available() else 'cpu'
warmup_rounds = 5  # Rounds before consensus starts

# LOAD PREPROCESSED MUSTARD DATA
def load_mustard_data():
    """Load preprocessed MUSTARD features"""
    print("Loading MUSTARD preprocessed data...")

    # Features for 3 clients
    utterance_features = np.load('mustard_utterance_features.npy')  # (690, 384)
    context_features = np.load('mustard_context_features.npy')      # (690, 384)
    speaker_features = np.load('mustard_speaker_features.npy')      # (690, num_speakers)
    labels = np.load('mustard_labels.npy')                          # (690,)

    # Splits
    train_idx = np.load('mustard_train_idx.npy')
    val_idx = np.load('mustard_val_idx.npy')
    test_idx = np.load('mustard_test_idx.npy')

    print(f"✓ Loaded {len(labels)} samples")
    print(f"  Train: {len(train_idx)}, Val: {len(val_idx)}, Test: {len(test_idx)}")
    print(f"  Utterance shape: {utterance_features.shape}")
    print(f"  Context shape: {context_features.shape}")
    print(f"  Speaker shape: {speaker_features.shape}")
    print(f"  Sarcasm rate: {labels.mean():.1%}")

    # Converting to torch tensors
    utterance_features = torch.FloatTensor(utterance_features)
    context_features = torch.FloatTensor(context_features)
    speaker_features = torch.FloatTensor(speaker_features)
    labels = torch.LongTensor(labels)

    return (utterance_features, context_features, speaker_features,
            labels, train_idx, val_idx, test_idx)

# CLIENT DATASETS FOR MULTIMODAL VFL
class MultimodalClientDataset(Dataset):
    def __init__(self, features, labels, indices):
        """
        Args:
            features: Tensor of features for this client
            labels: All labels
            indices: Train/val/test indices
        """
        self.features = features[indices]
        self.labels = labels[indices]

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]

def prepare_multimodal_dataloaders(client_features, labels, train_idx, val_idx, test_idx, batch_size=32):
    """Prepare dataloaders for 3 clients (utterance, context, speaker)"""
    num_clients = len(client_features)

    client_train_loaders = []
    client_val_loaders = []
    client_test_loaders = []

    for i in range(num_clients):
        # Datasets
        train_dataset = MultimodalClientDataset(client_features[i], labels, train_idx)
        val_dataset = MultimodalClientDataset(client_features[i], labels, val_idx)
        test_dataset = MultimodalClientDataset(client_features[i], labels, test_idx)

        # Dataloaders
        train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True,
                                 num_workers=0, pin_memory=True)
        val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False,
                               num_workers=0, pin_memory=True)
        test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False,
                                num_workers=0, pin_memory=True)

        client_train_loaders.append(train_loader)
        client_val_loaders.append(val_loader)
        client_test_loaders.append(test_loader)

    return client_train_loaders, client_val_loaders, client_test_loaders

# IMPROVED MULTI-LAYER GNN WITH ATTENTION
class AttentionGNNLayer(nn.Module):
    def __init__(self, input_dim, output_dim, num_heads=4):
        super(AttentionGNNLayer, self).__init__()
        self.input_dim = input_dim
        self.output_dim = output_dim
        self.num_heads = num_heads
        self.head_dim = output_dim // num_heads

        assert output_dim % num_heads == 0, "output_dim must be divisible by num_heads"

        # Multi-head attention components
        self.q_linear = nn.Linear(input_dim, output_dim)
        self.k_linear = nn.Linear(input_dim, output_dim)
        self.v_linear = nn.Linear(input_dim, output_dim)
        self.out_linear = nn.Linear(output_dim, output_dim)

        # Standard GNN transformation
        self.theta = nn.Parameter(torch.randn(input_dim, output_dim) * 0.01)

        # Combination weights
        self.alpha = nn.Parameter(torch.tensor(0.5))

        self.dropout = nn.Dropout(0.2)
        self.layer_norm = nn.LayerNorm(output_dim)

    def forward(self, H, W):
        batch_size, num_nodes, input_dim = H.shape

        # Standard GNN path with adjacency matrix
        gnn_out = torch.relu(torch.matmul(torch.matmul(W, H), self.theta))

        # Multi-head attention path
        Q = self.q_linear(H).view(batch_size, num_nodes, self.num_heads, self.head_dim)
        K = self.k_linear(H).view(batch_size, num_nodes, self.num_heads, self.head_dim)
        V = self.v_linear(H).view(batch_size, num_nodes, self.num_heads, self.head_dim)

        # Attention scores
        scores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(self.head_dim)
        attention_weights = torch.softmax(scores, dim=-1)
        attention_weights = self.dropout(attention_weights)

        # Apply attention
        attention_out = torch.matmul(attention_weights, V)
        attention_out = attention_out.view(batch_size, num_nodes, self.output_dim)
        attention_out = self.out_linear(attention_out)

        # GNN and attention- combine
        combined = torch.sigmoid(self.alpha) * gnn_out + (1 - torch.sigmoid(self.alpha)) * attention_out

        # Residual connection if dimensions match
        if input_dim == self.output_dim:
            combined = combined + H

        return self.layer_norm(combined)

class MultiLayerGNN(nn.Module):
    def __init__(self, input_dim, hidden_dims, num_heads=4):
        super(MultiLayerGNN, self).__init__()
        self.layers = nn.ModuleList()

        # First layer
        self.layers.append(AttentionGNNLayer(input_dim, hidden_dims[0], num_heads))

        # Hidden layers
        for i in range(1, len(hidden_dims)):
            self.layers.append(AttentionGNNLayer(hidden_dims[i-1], hidden_dims[i], num_heads))

    def forward(self, H, W):
        for layer in self.layers:
            H = layer(H, W)
        return H

# MULTIMODAL-AWARE ADJACENCY INITIALIZATION
def create_multimodal_adjacency(feature_dim, modality_type='text'):
    """
    Now we create a multimodal adjacency matrix.
    Args:
        feature_dim: Number of feature dimensions
        modality_type: 'text', 'context', or 'speaker'
    """
    W = torch.zeros(feature_dim, feature_dim)

    if modality_type == 'text' or modality_type == 'context':
        # For text embeddings: nearby dimensions often capture related semantics
        for i in range(feature_dim):
            for j in range(feature_dim):
                # Gaussian kernel based on distance
                dist = abs(i - j)
                W[i, j] = math.exp(-dist**2 / (2 * (feature_dim/10)**2))

    elif modality_type == 'speaker':
        # For one-hot speaker: all speakers potentially related
        W = torch.ones(feature_dim, feature_dim) * 0.3
        # Diagonal slightly stronger (self-identity)
        W.fill_diagonal_(1.0)

    # Normalize
    W = W / (W.sum(dim=1, keepdim=True) + 1e-8)

    return W

# ENHANCED MULTIMODAL CLIENT MODEL
class MultimodalClientModel(nn.Module):
    def __init__(self, input_dim, modality_type='text', gnn_hidden_dims=[128, 64],
                 mlp_hidden=64, num_classes=2, sparsity_reg=5e-5):
        super(MultimodalClientModel, self).__init__()
        self.input_dim = input_dim
        self.modality_type = modality_type
        self.sparsity_reg = sparsity_reg

        # Feature encoder
        self.feature_encoder = nn.Sequential(
            nn.Linear(input_dim, 128),
            nn.LayerNorm(128),
            nn.ReLU(),
            nn.Dropout(0.3)
        )

        # Initialization of adjacency with modality-specific priors
        adjacency_prior = create_multimodal_adjacency(128, modality_type)
        self.W = nn.Parameter(adjacency_prior * 0.1 + torch.randn(128, 128) * 0.01)

        # Multi-layer GNN with attention
        self.gnn = MultiLayerGNN(input_dim=1, hidden_dims=gnn_hidden_dims, num_heads=4)

        # Enhanced classifier with dropout and batch norm
        final_gnn_dim = gnn_hidden_dims[-1]
        self.classifier = nn.Sequential(
            nn.Linear(128 * final_gnn_dim, mlp_hidden * 2),
            nn.BatchNorm1d(mlp_hidden * 2),
            nn.ReLU(),
            nn.Dropout(0.4),
            nn.Linear(mlp_hidden * 2, mlp_hidden),
            nn.BatchNorm1d(mlp_hidden),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(mlp_hidden, num_classes)
        )

    def forward(self, x):
        B = x.size(0)

        # Encoding features to uniform space
        x_encoded = self.feature_encoder(x)  # (B, 128)

        # Reshape for GNN: (batch, num_features, 1)
        H0 = x_encoded.view(B, 128, 1)

        # Adjacency matrix normalization
        W_norm = self.W / (self.W.norm(dim=1, keepdim=True) + 1e-6)

        # Multi-layer GNN
        H_out = self.gnn(H0, W_norm)  # (B, 128, hidden_dim)

        # Flatten for classification
        H_flat = H_out.view(B, -1)

        return self.classifier(H_flat)

    def get_sparsity_loss(self):
        """L1 regularization on adjacency matrix"""
        return self.sparsity_reg * torch.norm(self.W, p=1)

# ADAPTIVE LEARNING RATE SCHEDULER
class CosineAnnealingWarmup:
    def __init__(self, optimizer, warmup_epochs, max_epochs, eta_min):
        self.optimizer = optimizer
        self.warmup_epochs = warmup_epochs
        self.max_epochs = max_epochs
        self.eta_min = eta_min
        self.base_lr = optimizer.param_groups[0]['lr']

    def step(self, epoch):
        if epoch < self.warmup_epochs:
            lr = self.base_lr * epoch / self.warmup_epochs
        else:
            lr = self.eta_min + (self.base_lr - self.eta_min) * 0.5 * (
                1 + math.cos(math.pi * (epoch - self.warmup_epochs) / (self.max_epochs - self.warmup_epochs))
            )

        for param_group in self.optimizer.param_groups:
            param_group['lr'] = lr

        return lr

# IMPROVED TRAINING WITH ADAPTIVE CONSENSUS
def get_ring_neighbors(k, K):
    """Ring topology neighbors"""
    return [(k - 1) % K, (k + 1) % K]

def adaptive_consensus_rate(round_idx, initial_alpha=0.5, min_alpha=0.1, decay_rate=0.02):
    """Adaptive consensus rate that decreases over time as per theory :) """
    return max(min_alpha, initial_alpha * math.exp(-decay_rate * round_idx))

def train_one_round(client_models, client_optimizers, client_schedulers,
                   client_loaders, round_idx, consensus=True):
    K = len(client_models)
    local_correct = [0] * K
    local_total = [0] * K
    local_losses = [0.0] * K
    loss_fn = nn.CrossEntropyLoss()

    # Local training phase
    for k in range(K):
        model = client_models[k]
        model.train()
        optimizer = client_optimizers[k]
        scheduler = client_schedulers[k]
        loader = client_loaders[k]

        total_loss = 0
        correct = 0
        total = 0

        for batch_x, batch_y in loader:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)
            optimizer.zero_grad()

            logits = model(batch_x)
            classification_loss = loss_fn(logits, batch_y)
            sparsity_loss = model.get_sparsity_loss()
            loss = classification_loss + sparsity_loss

            loss.backward()

            # Gradient clipping
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

            optimizer.step()

            preds = torch.argmax(logits, dim=1)
            correct += (preds == batch_y).sum().item()
            total += batch_y.size(0)
            total_loss += classification_loss.item()

        scheduler.step(round_idx)
        local_correct[k] = correct
        local_total[k] = total
        local_losses[k] = total_loss / len(loader)

    # Consensus phase (with warmup)
    if consensus and round_idx > warmup_rounds:
        current_alpha = adaptive_consensus_rate(round_idx - warmup_rounds, α, 0.1)
        W_updates = [model.W.clone().detach() for model in client_models]

        for k in range(K):
            neighbors = get_ring_neighbors(k, K)
            consensus_W = (1 - current_alpha) * W_updates[k]
            for n in neighbors:
                consensus_W += (current_alpha / len(neighbors)) * W_updates[n]
            client_models[k].W.data = consensus_W

    accs = [100.0 * c / t if t > 0 else 0 for c, t in zip(local_correct, local_total)]
    global_acc = sum(accs) / K

    return global_acc

@torch.no_grad()
def validate_one_round(client_models, client_val_loaders):
    """Validation during training"""
    K = len(client_models)
    local_correct = [0] * K
    local_total = [0] * K

    for k in range(K):
        model = client_models[k]
        model.eval()
        loader = client_val_loaders[k]

        correct = 0
        total = 0

        for batch_x, batch_y in loader:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)
            logits = model(batch_x)
            preds = torch.argmax(logits, dim=1)
            correct += (preds == batch_y).sum().item()
            total += batch_y.size(0)

        local_correct[k] = correct
        local_total[k] = total

    accs = [100.0 * c / t if t > 0 else 0 for c, t in zip(local_correct, local_total)]
    global_val_acc = sum(accs) / K

    return global_val_acc

def run_training_with_validation(client_models, client_optimizers, client_schedulers,
                                 train_loaders, val_loaders, num_rounds=T, verbose=False):
    """Training with validation"""
    if verbose:
        print("\n" + "="*60)
        print("VFL-GNN training on MUSTARD dataset...")
        print("="*60)

    best_val_acc = 0
    patience = 15
    patience_counter = 0

    for t in range(1, num_rounds + 1):
        # Training
        train_acc = train_one_round(client_models, client_optimizers, client_schedulers,
                                    train_loaders, t)

        # Validation- every 5 rounds
        if t % 5 == 0:
            val_acc = validate_one_round(client_models, val_loaders)

            if verbose:
                print(f"[Round {t:3d}] Train Acc: {train_acc:.2f}% | Val Acc: {val_acc:.2f}%")

            # Early stopping
            if val_acc > best_val_acc:
                best_val_acc = val_acc
                patience_counter = 0
            else:
                patience_counter += 1

            if patience_counter >= patience:
                if verbose:
                    print(f"\n⚠️  Early stopping at round {t} (best val: {best_val_acc:.2f}%)")
                break
        elif verbose and t % 10 == 0:
            print(f"[Round {t:3d}] Train Acc: {train_acc:.2f}%")

    if verbose:
        print(f"\n✓ Training complete! Best validation accuracy: {best_val_acc:.2f}%")

    return best_val_acc

# COMPREHENSIVE EVALUATION WITH METRICS
@torch.no_grad()
def evaluate_clients_comprehensive(client_models, client_test_loaders):
    """Evaluate each client with comprehensive metrics"""
    K = len(client_models)
    local_correct = [0] * K
    local_total = [0] * K
    all_preds = [[] for _ in range(K)]
    all_labels = [[] for _ in range(K)]

    for k in range(K):
        model = client_models[k]
        loader = client_test_loaders[k]
        model.eval()

        for batch_x, batch_y in loader:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)
            logits = model(batch_x)
            preds = torch.argmax(logits, dim=1)

            all_preds[k].extend(preds.cpu().numpy())
            all_labels[k].extend(batch_y.cpu().numpy())

        local_correct[k] = sum([1 for p, l in zip(all_preds[k], all_labels[k]) if p == l])
        local_total[k] = len(all_labels[k])

    # Metrics
    individual_accuracies = [100.0 * c / t for c, t in zip(local_correct, local_total)]
    individual_f1s = [f1_score(all_labels[k], all_preds[k], average='binary') * 100 for k in range(K)]
    individual_precisions = [precision_score(all_labels[k], all_preds[k], average='binary') * 100 for k in range(K)]
    individual_recalls = [recall_score(all_labels[k], all_preds[k], average='binary') * 100 for k in range(K)]

    return (individual_accuracies, individual_f1s, individual_precisions,
            individual_recalls, all_preds, all_labels)

@torch.no_grad()
def evaluate_ensemble_comprehensive(client_models, client_test_loaders):
    """Ensemble evaluation with all metrics"""
    K = len(client_models)
    all_predictions = []
    all_labels = []

    # Predictions from all models
    for k in range(K):
        model = client_models[k]
        loader = client_test_loaders[k]
        model.eval()

        model_predictions = []
        labels = []

        for batch_x, batch_y in loader:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)
            logits = model(batch_x)
            probs = F.softmax(logits, dim=1)
            model_predictions.append(probs.cpu())
            labels.append(batch_y.cpu())

        all_predictions.append(torch.cat(model_predictions, dim=0))
        if k == 0:  # Labels are same for all clients as per assummption
            all_labels = torch.cat(labels, dim=0)

    # Ensemble prediction (average probabilities)
    ensemble_probs = torch.stack(all_predictions, dim=0).mean(dim=0)
    ensemble_preds = torch.argmax(ensemble_probs, dim=1)

    # Metrics
    correct = (ensemble_preds == all_labels).sum().item()
    total = all_labels.size(0)
    ensemble_accuracy = 100.0 * correct / total

    # Additional metrics
    ensemble_f1 = f1_score(all_labels.numpy(), ensemble_preds.numpy(), average='binary') * 100
    ensemble_precision = precision_score(all_labels.numpy(), ensemble_preds.numpy(), average='binary') * 100
    ensemble_recall = recall_score(all_labels.numpy(), ensemble_preds.numpy(), average='binary') * 100

    # Confusion matrix
    cm = confusion_matrix(all_labels.numpy(), ensemble_preds.numpy())

    return (ensemble_accuracy, ensemble_f1, ensemble_precision,
            ensemble_recall, cm, ensemble_preds.numpy(), all_labels.numpy())

# MAIN EXPERIMENT RUNNER
def run_mustard_experiment(verbose=True):
    """Run complete VFL-GNN experiment on MUSTARD"""
    if verbose:
        print("\n" + "="*80)
        print("🎭 VFL-GNN ON MUSTARD SARCASM DETECTION")
        print("="*80)

    start_time = time.time()

    # Data loading
    (utterance_features, context_features, speaker_features,
     labels, train_idx, val_idx, test_idx) = load_mustard_data()

    # 3 clients setup (utterance, context, speaker)
    client_features = [utterance_features, context_features, speaker_features]
    modality_types = ['text', 'context', 'speaker']
    modality_names = ['Utterance', 'Context', 'Speaker']

    train_loaders, val_loaders, test_loaders = prepare_multimodal_dataloaders(
        client_features, labels, train_idx, val_idx, test_idx, batch_size
    )

    # Models Initialization for 3 clients
    client_models = []
    for i in range(3):
        input_dim = client_features[i].shape[1]
        model = MultimodalClientModel(
            input_dim=input_dim,
            modality_type=modality_types[i],
            gnn_hidden_dims=[128, 64],
            mlp_hidden=64,
            num_classes=2
        ).to(device)
        client_models.append(model)

    if verbose:
        print(f"\n📊 Model Architecture:")
        for i, name in enumerate(modality_names):
            print(f"  Client {i+1} ({name}): {client_features[i].shape[1]}-dim → GNN → Binary Classifier")

    # Optimizers
    client_optimizers = [torch.optim.AdamW(model.parameters(), lr=η_initial, weight_decay=1e-4)
                        for model in client_models]

    # Schedulers
    client_schedulers = [CosineAnnealingWarmup(opt, warmup_epochs=warmup_rounds,
                                               max_epochs=T, eta_min=η_min)
                        for opt in client_optimizers]

    # Training
    best_val_acc = run_training_with_validation(
        client_models, client_optimizers, client_schedulers,
        train_loaders, val_loaders, num_rounds=T, verbose=verbose
    )

    # Evaluation
    if verbose:
        print("\n" + "="*80)
        print("📊 EVALUATION ON TEST SET")
        print("="*80)

    (individual_accuracies, individual_f1s, individual_precisions,
     individual_recalls, _, _) = evaluate_clients_comprehensive(client_models, test_loaders)

    (ensemble_accuracy, ensemble_f1, ensemble_precision,
     ensemble_recall, cm, _, _) = evaluate_ensemble_comprehensive(client_models, test_loaders)

    training_time = time.time() - start_time

    # Individual client results
    if verbose:
        print("\n📈 Individual Client Performance:")
        print("-" * 80)
        for i, name in enumerate(modality_names):
            print(f"\nClient {i+1} ({name}):")
            print(f"  Accuracy:  {individual_accuracies[i]:.2f}%")
            print(f"  F1 Score:  {individual_f1s[i]:.2f}%")
            print(f"  Precision: {individual_precisions[i]:.2f}%")
            print(f"  Recall:    {individual_recalls[i]:.2f}%")

        # Averages
        avg_acc = sum(individual_accuracies) / len(individual_accuracies)
        avg_f1 = sum(individual_f1s) / len(individual_f1s)
        avg_prec = sum(individual_precisions) / len(individual_precisions)
        avg_rec = sum(individual_recalls) / len(individual_recalls)

        print("\n" + "-" * 80)
        print("📊 Average Individual Performance:")
        print(f"  Accuracy:  {avg_acc:.2f}%")
        print(f"  F1 Score:  {avg_f1:.2f}%")
        print(f"  Precision: {avg_prec:.2f}%")
        print(f"  Recall:    {avg_rec:.2f}%")

        # Ensemble results
        print("\n" + "="*80)
        print("🏆 ENSEMBLE PERFORMANCE:")
        print("="*80)
        print(f"  Accuracy:  {ensemble_accuracy:.2f}%")
        print(f"  F1 Score:  {ensemble_f1:.2f}%")
        print(f"  Precision: {ensemble_precision:.2f}%")
        print(f"  Recall:    {ensemble_recall:.2f}%")

        # Improvement
        improvement_acc = ensemble_accuracy - avg_acc
        improvement_f1 = ensemble_f1 - avg_f1
        print(f"\n✨ Improvement over average:")
        print(f"  Accuracy:  +{improvement_acc:.2f}%")
        print(f"  F1 Score:  +{improvement_f1:.2f}%")

        # Confusion matrix
        print(f"\n📋 Confusion Matrix:")
        print(f"  TN: {cm[0,0]:3d} | FP: {cm[0,1]:3d}")
        print(f"  FN: {cm[1,0]:3d} | TP: {cm[1,1]:3d}")

        print(f"\n⏱️  Training Time: {training_time:.1f}s")
        print("="*80)

    # Result dictionary
    results = {
        'modality_names': modality_names,
        'individual_accuracies': individual_accuracies,
        'individual_f1s': individual_f1s,
        'individual_precisions': individual_precisions,
        'individual_recalls': individual_recalls,
        'avg_individual_accuracy': avg_acc,
        'avg_individual_f1': avg_f1,
        'avg_individual_precision': avg_prec,
        'avg_individual_recall': avg_rec,
        'ensemble_accuracy': ensemble_accuracy,
        'ensemble_f1': ensemble_f1,
        'ensemble_precision': ensemble_precision,
        'ensemble_recall': ensemble_recall,
        'confusion_matrix': cm,
        'training_time': training_time,
        'best_val_accuracy': best_val_acc
    }

    return results

# RESULTS TABLE
def create_results_table(results):
    """Create a formatted results table"""

    # Client-wise results
    client_data = []
    for i, name in enumerate(results['modality_names']):
        client_data.append({
            'Client': f'{i+1} ({name})',
            'Accuracy': f"{results['individual_accuracies'][i]:.2f}%",
            'F1 Score': f"{results['individual_f1s'][i]:.2f}%",
            'Precision': f"{results['individual_precisions'][i]:.2f}%",
            'Recall': f"{results['individual_recalls'][i]:.2f}%"
        })

    # Average
    client_data.append({
        'Client': 'Average',
        'Accuracy': f"{results['avg_individual_accuracy']:.2f}%",
        'F1 Score': f"{results['avg_individual_f1']:.2f}%",
        'Precision': f"{results['avg_individual_precision']:.2f}%",
        'Recall': f"{results['avg_individual_recall']:.2f}%"
    })

    # Ensemble
    client_data.append({
        'Client': 'Ensemble',
        'Accuracy': f"{results['ensemble_accuracy']:.2f}%",
        'F1 Score': f"{results['ensemble_f1']:.2f}%",
        'Precision': f"{results['ensemble_precision']:.2f}%",
        'Recall': f"{results['ensemble_recall']:.2f}%"
    })

    df = pd.DataFrame(client_data)

    return df

# MAIN
if __name__ == "__main__":
    # Device info
    print(f"\n🔧 Using device: {device}")
    if device == 'cuda':
        print(f"🔧 GPU: {torch.cuda.get_device_name()}")

    # Running experiment
    results = run_mustard_experiment(verbose=True)

    # Results table
    results_table = create_results_table(results)

    print("\n" + "="*80)
    print("📊 COMPREHENSIVE RESULTS TABLE")
    print("="*80)
    print(results_table.to_string(index=False))

    # Saved Results
    results_table.to_csv('mustard_vfl_gnn_results.csv', index=False)
    print(f"\n💾 Results saved to 'mustard_vfl_gnn_results.csv'")

    print("\n✅ Experiment Complete!")
    print(f"🎉 Ensemble achieved {results['ensemble_accuracy']:.2f}% accuracy with {results['ensemble_f1']:.2f}% F1 score!")